# Generated by Django 4.2.22 on 2025-07-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100, unique=True)),
                ('subjectCode', models.CharField(max_length=7, unique=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
            options={
                'ordering': ('subjectName',),
            },
        ),
    ]
