# Generated by Django 4.2.22 on 2025-07-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=100),
        ),
    ]
