# Generated by Django 4.2.22 on 2025-07-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('subjectId', 'classId')},
        ),
    ]
