# Generated by Django 4.2.22 on 2025-07-09 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('childId', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('A', 'admin'), ('P', 'parent'), ('S', 'student'), ('T', 'teacher')], default='S', unique=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='M')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('entrance', models.DateTimeField()),
                ('dob', models.DateTimeField()),
                ('address', models.CharField(max_length=400)),
                ('nationality', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('zipCode', models.CharField(max_length=8)),
                ('telephone', models.CharField(max_length=11)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
