# Generated by Django 4.2.22 on 2025-07-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('entrance', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateTimeField()),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('A', 'admin'), ('P', 'parent'), ('S', 'student'), ('T', 'teacher')], default='S')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='M')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('classId', models.CharField(blank=True)),
                ('childId', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('nationality', models.CharField(blank=True, max_length=70)),
                ('state', models.CharField(blank=True, max_length=70)),
                ('zipCode', models.CharField(blank=True, max_length=8)),
                ('telephone', models.CharField(blank=True, max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('firstName', 'lastName'),
            },
        ),
    ]
