# Generated by Django 4.2.22 on 2025-07-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='regNo',
            new_name='username',
        ),
    ]
