# Generated by Django 4.2.22 on 2025-07-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('account', '0002_alter_user_address_alter_user_childid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.class'),
        ),
    ]
