# Generated by Django 4.2.22 on 2025-07-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('account', '0004_alter_user_dob_alter_user_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classId',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='classes.class'),
        ),
    ]
