# Generated by Django 4.2.22 on 2025-07-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('account', '0005_alter_user_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class'),
        ),
    ]
