# Generated by Django 4.2.22 on 2025-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classId',
            field=models.CharField(blank=True),
        ),
    ]
