# Generated by Django 4.2.22 on 2025-07-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
