# Generated by Django 4.2.22 on 2025-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entrance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
