# Generated by Django 4.2.22 on 2025-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('T', 'teacher'), ('M', 'admin'), ('S', 'student'), ('P', 'parent')], default='S'),
        ),
    ]
