# Generated by Django 4.2.22 on 2025-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('admin', 'admin'), ('student', 'student'), ('parent', 'parent')], default='student'),
        ),
    ]
