# Generated by Django 4.2.22 on 2025-07-14 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('attendance', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('attendance', 'date'),
            },
        ),
    ]
