# Generated by Django 4.2.22 on 2025-09-11 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('complaint', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('replyStatus', models.BooleanField()),
                ('replyMessage', models.TextField(blank=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title', 'classId', 'date'),
            },
        ),
    ]
