# Generated by Django 4.2.22 on 2025-10-14 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examScore', models.CharField(blank=True)),
                ('test_score1', models.CharField(blank=True)),
                ('test_score2', models.CharField(blank=True)),
                ('test_score3', models.CharField(blank=True)),
                ('homework_score1', models.CharField(blank=True)),
                ('homework_score2', models.CharField(blank=True)),
                ('homework_score3', models.CharField(blank=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('subjectId', 'classId'),
            },
        ),
    ]
